src/webapps/Web.Mvc/Models/ErrorViewModel.cs
namespace Web.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/webapps/Web.Mvc/Models/Product.cs
namespace Web.Mvc.Models;

public class Product
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty;

    public string ImgUrl { get; set; } = string.Empty;

    public string Description { get; set; } = string.Empty;

    public decimal Price { get; set; }
}

src/webapps/Web.Mvc/Models/ProductVariant.cs
namespace Web.Mvc.Models;

public class ProductVariant
{
    public string Id { get; set; }
    public decimal Price { get; set; }
    public decimal OriginalPrice { get; set; }
    public string ProductType { get; set; }
}

src/webapps/Web.Mvc/Controllers/HomeController.cs
// <copyright file="HomeController.cs" company="Patrik Duch">
// Copyright (c) Patrik Duch, IČ: 09225471
// </copyright>
namespace Web.Mvc.Controllers;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Models;
using System.Diagnostics;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        LogTokenAndClaim();

        return View();
    }

    [Authorize]
    public IActionResult Privacy()
    {
        return View();
    }

    /// <summary>
    /// Asynchronously signs the user out from the application.
    /// </summary>
    /// <returns>A task that represents the asynchronous logout operation.</returns>
    [Authorize]
    public async Task Logout()
    {
        // Sign the user out from the application by invalidating the authentication cookie.
        // This removes the cookie that keeps track of the user's authenticated session.
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

        // Sign the user out from the OpenID Connect session.
        // This sends a request to the OpenID Connect server to end the user's session.
        await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
    }

    public async Task LogTokenAndClaim()
    {
        var identityToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.IdToken);

        Debug.WriteLine($"Identity token: {identityToken}");

        foreach (var userClaim in User.Claims)
        {
            Debug.WriteLine($"Claim type {userClaim.Type} - Claim value: {userClaim.Value}");
        }
    }

    /// <summary>
    /// View for managing error states in the application.
    /// </summary>
    // "Duration = 0" means this response is not cached.
    // "Location = ResponseCacheLocation.None" means the response cannot be stored in any cache location.
    // "NoStore = true" directs that the response should not be stored in the cache.
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/webapps/Web.Mvc/Controllers/ProductController.cs
namespace Web.Mvc.Controllers;

using ApiServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

public class ProductController : Controller
{
    private readonly IProductService _productService;

    public ProductController(IProductService productService)
    {
        _productService = productService;
    }


    // GET: ProductController1cs
    [Authorize]
    public async Task<ActionResult> Index()
    {
        var products = await _productService.GetProductAsync(Guid.NewGuid());


        return View(products);
    }
}

src/webapps/Web.Mvc/Controllers/UserController.cs
namespace Web.Mvc.Controllers;

using ApiServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

public class UserController : Controller
{
    private readonly IIdentityService _identityService;

    public UserController(IIdentityService identityService)
    {
        _identityService = identityService;
    }

    [Authorize]
    public async Task<IActionResult> Profile()
    {
        var authenticateResult = await HttpContext.AuthenticateAsync("Cookies");
        var accessToken = authenticateResult.Properties.GetTokenValue("access_token");
        
        var userProfile = await _identityService.GetUserProfileInfo(accessToken, CancellationToken.None);

        return View(userProfile);
    }
}

src/webapps/Web.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/webapps/Web.Mvc/Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@using NetMicroservices.ServiceConfig.Nuget;

@model ServiceResponse<List<Product>>;


<h1>Products</h1>

@foreach (var item in Model.Data)
{
    <h2>@item.Name</h2>
}

src/webapps/Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/webapps/Web.Mvc/Views/User/Profile.cshtml
@*
    View to display user details (profile) from IdentityServer 4.
*@

@using Web.Mvc.Models.Identity;
@model IdentityProfileModel


<h1>Your profile</h1>

<p>FirstName: @Model.GivenName </p>
<p>Surname: @Model.FamilyName </p>